#! /usr/bin/env bash
set -e
initial_wd=`pwd`
# just in case
export WHEEL_TOOL=/Users/sth/dev/convertbng/venv/bin/wheel
# build rust binary
cd ../latlong_bng
cargo test
cargo build --release
echo "Testing and release build complete. Copying binary…"
cd $initial_wd
cp ../latlong_bng/target/release/liblonlat_bng.dylib convertbng/
echo "Removing build and dist dir"
rm -rf build
rm -rf dist
echo "Packaging source and binary"
python setup.py bdist_wheel sdist
echo "Uploading to PyPI"
# https://pypi.python.org/pypi/twine/
twine upload dist/* --sign --identity 39C1ED9A
echo "Finished uploading"
exit 0
